language: cpp

compiler:
  - clang

script:
  - make tests


notifications:
  email:
    recipients:
      - rz1216@nyu.edu
    on_success: always
    on_failure: never

    recipients:
      - bw1417@nyu.edu
    on_success: always
    on_failure: always  
